Replace workflow doc with releasing doc
globus/action-provider-tools pull request #141
Opened 2024-04-11 15:37 UTC by sirosen

Simpler process, simpler doc, focused only on what we need.
Discard misleading and overly verbose internal documentation.

2024-04-11 16:52 UTC, kurtmckee requested changes
This decimates the git workflow, hotfixes, and having a release branch.

2024-04-11 17:09 UTC, sirosen commented
Yes, but not by accident. This is an intentional simplification because the current documentation does not provide what I view as useful and necessary for the maintenance of this library. It is also loaded with additional information which is distracting and in several cases inaccurate or unhelpful. 

Clearly we will need to discuss to reach some resolution. I need a doc which I can cat in the repo and which tells me the steps for a release. I do not want -- and contend that we do not need -- a document which explains that features are developed in branches, or that semver breaks the version number into three digital segments. (If we want to document that we use semver, a statement of that fact plus a link would suffice.)

Since we tag releases, we in no way lose the ability to patch a past release. However, such documentation (if any -- I don't see that we need any) should be intentionally isolated from standard procedures, as it is an exceptional case for a published library.

2024-04-11 17:30 UTC, sirosen commented
I'm going to thin this changeset down to what I consider essential:
- no workflow changes (although I really _would_ like to change our workflow too, in order to make things even more streamlined)
- rather than removing the whole workflow doc, I'll simply remove any parts which becomes redundant (and therefore a source of error/drift/disagreement) with the new release doc
- still adds a release doc, but conforms to the "create and tag a release branch" pattern

2024-10-16 21:14 UTC, kurtmckee requested changes

2024-10-16 21:18 UTC, sirosen commented on RELEASING.md
> +- Merge `production` back to `main`; `git checkout main; git merge production`
Yeah, let's do it based off of the existing commands for services using this pattern, a `gh pr create ...` which includes the date.

2024-10-16 21:20 UTC, sirosen commented on RELEASING.md
> +- Merge `production` back to `main`; `git checkout main; git merge production`
Added; take a look and LMK!

2024-10-16 21:23 UTC, kurtmckee approved these changes

2024-10-16 21:24 UTC, merged